name: Documentation Deployment
on: [push, pull_request]

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-
      - run: pip install mkdocs mkdocs-awesome-pages-plugin mkdocs-markdownextradata-plugin
      - run: mkdocs gh-deploy --force --clean --verbose