name: Unit Tests Matrix

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
            - python-version: '3.7'
              numpy-version: '>=1.15,<1.16'
              setuptools-version: '>=40.0,<41.0'
              pip-version: '>=18.0,<19.0'
              wheel-version: '>=0.32,<0.33'
              pyyaml-version: '>=3.13,<3.14'
            - python-version: '3.8'
              numpy-version: '>=1.18,<1.19'
              setuptools-version: '>=41.5,<42.0'
              pip-version: '>=19.3,<20.0'
              wheel-version: '>=0.34,<0.35'
              pyyaml-version: '>=5.2,<5.3'
            - python-version: '3.9'
              numpy-version: '>=1.20,<1.21'
              setuptools-version: '>=51.0,<52.0'
              pip-version: '>=20.3,<21.0'
              wheel-version: '>=0.36,<0.37'
              pyyaml-version: '>=5.4,<5.5'
            - python-version: '3.10'
              numpy-version: '>=1.22,<1.23'
              setuptools-version: '>=58.5,<59.0'
              pip-version: '>=21.3,<22.0'
              wheel-version: '>=0.38,<0.39'
              pyyaml-version: '>=6.0,<6.1'
            - python-version: '3.11'
              numpy-version: '>=1.24,<1.25'
              setuptools-version: '>=65.6,<66.0'
              pip-version: '>=23.0,<24.0'
              wheel-version: '>=0.40,<0.41'
              pyyaml-version: '>=6.0,<6.1'
            - python-version: '3.12'
              numpy-version: '>=1.26,<1.27'
              setuptools-version: '>=69.0,<70.0'
              pip-version: '>=23.3,<24.0'
              wheel-version: '>=0.42,<0.43'
              pyyaml-version: '>=6.0,<6.1'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install "pip${{ matrix.pip-version }}"
        pip install "setuptools${{ matrix.setuptools-version }}"
        pip install "wheel${{ matrix.wheel-version }}"
        pip install "numpy${{ matrix.numpy-version }}"
        pip install "pyyaml${{ matrix.pyyaml-version }}"
        
    - name: Run unit tests
      run: |
        python -m unittest discover arcann_training/unittests
